export const STATUS={OBSERVED:'OBSERVED',VERIFIED:'VERIFIED',PROVIDER_SUPPLIED:'PROVIDER_SUPPLIED',USER_PROVIDED:'USER_PROVIDED',CALCULATED:'CALCULATED',ASSUMED:'ASSUMED',ESTIMATED:'ESTIMATED',SCENARIO:'SCENARIO',MISSING:'MISSING'};
export const VAT_RATE=15;
export const clamp=(n,min,max)=>Math.min(Math.max(Number(n)||0,min),max);
export const fmtMoney=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n)||0);
export const fmtNum=n=>new Intl.NumberFormat('en-ZA',{maximumFractionDigits:0}).format(Number(n)||0);
export const fmtPct=n=>`${(Number(n)||0).toFixed(1)}%`;
export function transferDuty(value){const v=Math.max(0,Number(value)||0);if(v<=1210000)return 0;if(v<=1663800)return (v-1210000)*.03;if(v<=2329300)return 13614+(v-1663800)*.06;if(v<=2994800)return 53544+(v-2329300)*.08;if(v<=13310000)return 106784+(v-2994800)*.11;return 1241456+(v-13310000)*.13;}
export function propertyVAT(price,{applicable=false,rate=15,priceIncludesVat=false}={}){const p=Math.max(0,Number(price)||0),r=Math.max(0,Number(rate)||15)/100;if(!applicable)return {amount:0,rate:rate,priceBasis:'NOT_APPLICABLE',grossConsideration:p};if(priceIncludesVat)return {amount:p-(p/(1+r)),rate:rate,priceBasis:'VAT_INCLUDED',grossConsideration:p};return {amount:p*r,rate:rate,priceBasis:'VAT_EXCLUDED',grossConsideration:p+p*r};}
export function annuityPayment(principal,annualRate,months){const p=Math.max(0,Number(principal)||0),n=Math.max(1,Math.round(Number(months)||1)),r=(Number(annualRate)||0)/100/12;if(r===0)return p/n;return p*r/(1-Math.pow(1+r,-n));}
export function financeQuote({price,deposit=0,rate=10.5,term=72,balloonPct=0,monthlyFee=69,initiationFee=1200}={}){const p=Math.max(0,Number(price)||0),d=clamp(deposit,0,p),principal=p-d,n=Math.max(1,Math.round(Number(term)||72)),bp=clamp(balloonPct,0,95)/100,B=principal*bp,r=(clamp(rate,0,100))/100/12;let base;if(r===0)base=(principal-B)/n;else base=(principal-B/Math.pow(1+r,n))*r/(1-Math.pow(1+r,-n));const fee=Math.max(0,Number(monthlyFee)||0),init=Math.max(0,Number(initiationFee)||0),scheduled=base+fee,totalInstallments=scheduled*n,totalPaid=d+totalInstallments+B+init;return {price:p,deposit:d,principal,balloon:B,term:n,rate:Number(rate)||0,basePayment:base,monthlyPayment:scheduled,monthlyFee:fee,initiationFee:init,totalInstallments,financeCharges:totalPaid-p,totalPaid,balloonPct:bp*100};}
function propertyAcquisition(asset){const vat=propertyVAT(asset.price,{applicable:!!asset.vatApplicable,rate:asset.vatRate||VAT_RATE,priceIncludesVat:!!asset.priceIncludesVat});const duty=asset.vatApplicable?0:transferDuty(asset.price);const legal=Math.max(0,Number(asset.transferLegalCostScenario)||0);const bond=Math.max(0,Number(asset.bondRegistrationScenario)||0);return {vat,duty,legal,bond,total:duty+vat.amount+legal+bond,grossPurchase:vat.grossConsideration};}
export function calcAssetOutcome(asset,options={}){const financeOn=options.finance!==false,insuranceOn=options.insurance!==false,horizon=Math.max(1,Math.round(Number(options.horizon)||60)),km=Math.max(0,Number(options.km)||1500),fuelPrice=Math.max(0,Number(options.fuelPrice)||26.92),mRate=Number(options.rate),term=Number(options.term)||72,deposit=Number(options.deposit)||0,balloonPct=Number(options.balloonPct)||0,monthlyFee=Number(options.monthlyFee)||0,initiationFee=Number(options.initiationFee)||0;const p=Math.max(0,Number(asset.price)||0);const selectedInsurance=options.insuranceProduct?insuranceQuote(asset,options.insuranceProduct):null;const insuranceMonthly=selectedInsurance?.premiumMonthly??options.insuranceMonthly;let acquisition=0,recurring=0,insurance=0,income=0,exitCosts=0,residual=Number(asset.futureValue)||0,detail={},financeBase=p;
if(asset.assetType==='property'){const acq=propertyAcquisition(asset);acquisition=acq.total;financeBase=acq.grossPurchase;const vacancy=1-clamp(asset.rentalVacancyPct,0,100)/100;income=Math.max(0,Number(asset.rentalMonthly)||0)*horizon*vacancy*(1+Math.max(0,Number(asset.rentalEscalationPct)||0)/100*(horizon/12)/2);recurring=(Math.max(0,Number(asset.ratesMonthly)||0)+Math.max(0,Number(asset.leviesMonthly)||0)+Math.max(0,Number(asset.maintenanceMonthly)||0)+Math.max(0,Number(asset.utilitiesMonthly)||0))*horizon;insurance=insuranceOn?Math.max(0,Number(insuranceMonthly??asset.insuranceMonthly)||0)*horizon:0;exitCosts=residual*clamp(asset.saleCostPct,0,100)/100;detail={...acq,transferDuty:acq.duty,vatAmount:acq.vat.amount,rates:Number(asset.ratesMonthly||0)*horizon,levies:Number(asset.leviesMonthly||0)*horizon,maintenance:Number(asset.maintenanceMonthly||0)*horizon,utilities:Number(asset.utilitiesMonthly||0)*horizon,rentalIncome:income,saleCosts:exitCosts};}
else if(asset.assetType==='jewellery'){const scenario=options.exitScenario||'future';const values={future:Number(asset.futureValue)||0,fairMarket:Number(asset.fairMarketValue)||0,trade:Number(asset.tradeValue)||0,scrap:Number(asset.scrapValue)||0};residual=values[scenario]??values.future;recurring=Math.max(0,Number(asset.storageMonthly)||0)*horizon;insurance=insuranceOn?Math.max(0,Number(insuranceMonthly??asset.insuranceMonthly)||0)*horizon:0;exitCosts=residual*clamp(asset.resaleCostPct,0,100)/100;detail={storage:recurring,insurance,valuation:Number(asset.valuation||0),replacementValue:Number(asset.replacementValue||0),fairMarketValue:values.fairMarket,tradeValue:values.trade,scrapValue:values.scrap,resaleCosts:exitCosts,exitScenario:scenario};}
else {const fuel=(Math.max(0,Number(asset.consumption)||0)/100)*km*fuelPrice*horizon;const maint=(Math.max(0,Number(asset.maintenanceMonthly)||0)+Math.max(0,Number(asset.licenceMonthly)||0)+Math.max(0,Number(asset.tyresMonthly)||0))*horizon;recurring=fuel+maint;insurance=insuranceOn?Math.max(0,Number(insuranceMonthly??asset.insuranceMonthly)||0)*horizon:0;residual=Number(asset.futureValue)||0;detail={fuel,fuelPrice,kmMonthly:km,maintenance:Number(asset.maintenanceMonthly||0)*horizon,licence:Number(asset.licenceMonthly||0)*horizon,tyres:Number(asset.tyresMonthly||0)*horizon};}
const fq=financeOn?financeQuote({price:financeBase,deposit,rate:Number.isFinite(mRate)?mRate:10.5,term,balloonPct,monthlyFee,initiationFee}):null;const financeCharges=fq?fq.financeCharges:0;const normalizedCost=(asset.assetType==='property' ? financeBase : p)+ (asset.assetType==='property'? (acquisition-propertyVAT(asset.price,{applicable:!!asset.vatApplicable,rate:asset.vatRate||VAT_RATE,priceIncludesVat:!!asset.priceIncludesVat}).amount):acquisition) + recurring+insurance+financeCharges+exitCosts;
const outcome=residual+income-normalizedCost;return {assetId:asset.id,purchasePrice:p,financeBase,acquisition,recurring,insurance,financeCharges,residual,income,exitCosts,economicCost:normalizedCost,outcome,monthlyEquivalent:(normalizedCost-income-residual)/horizon,financeQuote:fq,detail,status:'CALCULATED'};}
export function insuranceQuote(asset,product){const p=product||{};const basis=asset.assetType==='jewellery'?(Number(asset.valuation)||Number(asset.price)||0):asset.assetType==='property'?(Number(asset.price)||0):(Number(asset.market)||Number(asset.price)||0);const premium=Math.max(0,basis*Number(p.premiumFactor||0));return {sumInsured:basis,premiumMonthly:premium,excess:Number(p.excess)||0,basis:p.sumInsuredBasis||'DEMO'};}
export function compareAssets(assets,options={}){return assets.map(a=>({...a,outcome:calcAssetOutcome(a,options)}));}
export function evidenceRows(asset){const e=asset.evidence||{};return Object.entries(e).map(([field,status])=>({field,status,source:field==='transferDuty'?'SARS published formula':status==='PROVIDER_SUPPLIED'?'Demo provider record':status==='MISSING'?'Production verification required':'Demo/scenario catalogue'}));}
