import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const sources=JSON.parse(fs.readFileSync(new URL('../data/sources.json',import.meta.url)));
const providers=JSON.parse(fs.readFileSync(new URL('../data/providers.json',import.meta.url)));
const checks=[]; const req=(name,pass,detail)=>checks.push({name,status:pass?'PASS':'FAIL',detail});
req('Demo boundary visible',html.includes('NOT A LIVE OFFER')&&html.includes('DEMO'), 'UI labels the demonstrator as demo/not-live.');
req('No live quote claim',html.includes('NO LIVE QUOTES')&&app.includes('not verified offers'), 'No UI claim that demo prices are live quotes.');
req('Affordability disclaimer',html.includes('not a lender affordability assessment')||app.includes('not a lender affordability assessment'),'Affordability is explicitly illustrative, not a lender credit decision.');
req('Advertising separation',html.includes('Advertising does not alter calculation inputs') && html.includes('SPONSORED'),'Sponsored content is separated from intelligence.');
req('Verification-ready language',html.includes('Verification-ready provider slot')||app.includes('Verification-ready provider slot'),'Provider verification is not falsely represented as completed.');
req('Evidence boundary',app.includes('missing evidence stays missing')&&app.includes('evidenceRows'),'Evidence states are explicit.');
req('POPIA source',sources.regulatory.some(s=>/Protection of Personal Information|POPIA/i.test(s.title)),'POPIA reference present.');
req('NCA source',sources.regulatory.some(s=>/National Credit Act/i.test(s.title)),'NCA reference present.');
req('Insurance Act source',sources.regulatory.some(s=>/Insurance Act/i.test(s.title)),'Insurance Act reference present.');
req('PPRA source',sources.regulatory.some(s=>/PPRA|Licensing/i.test(s.title)),'PPRA reference present.');
req('SADPMR source',sources.regulatory.some(s=>/SADPMR|Licences|Registers/i.test(s.authority+s.title)),'SADPMR reference present.');
req('SARS source',sources.regulatory.some(s=>/Transfer Duty/i.test(s.title)),'SARS transfer-duty reference present.');
req('DMPR source',sources.regulatory.some(s=>/Fuel/i.test(s.title)),'DMPR fuel reference present.');
req('Finance providers are demo',providers.finance.every(p=>p.evidence==='DEMO'),'No finance provider is presented as live/verified.');
req('Insurance providers are demo',providers.insurance.every(p=>p.evidence==='DEMO'),'No insurer is presented as live/verified.');
req('No automatic recommendation label',!/\b(best|recommended|approved|eligible)\b/i.test(html.replace(/<[^>]+>/g,' ')),'UI does not claim best/recommended/approved/eligible status.');
const fails=checks.filter(x=>x.status==='FAIL');
console.log(JSON.stringify({suite:'VECTORI compliance guardrail audit',checks,failures:fails.length,status:fails.length?'FAIL':'PASS'},null,2));
if(fails.length) process.exit(1);
