import assert from 'node:assert/strict';
import fs from 'node:fs';
import {transferDuty,propertyVAT,financeQuote,annuityPayment,calcAssetOutcome,compareAssets,insuranceQuote,evidenceRows} from '../engine.js';
const inv=JSON.parse(fs.readFileSync(new URL('../data/inventory.json',import.meta.url)));
const providers=JSON.parse(fs.readFileSync(new URL('../data/providers.json',import.meta.url)));
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
let passed=0; const ok=(c,l)=>{assert.ok(c,l);passed++}; const near=(a,b,l)=>ok(Math.abs(a-b)<0.01,l);
for(const m of ['automotive','property','jewellery']){ok(inv[m].length===10,`${m}: 10 assets`);ok(new Set(inv[m].map(x=>x.id)).size===10,`${m}: unique IDs`);ok(new Set(inv[m].map(x=>x.providerId)).size===10,`${m}: 10 asset providers`);ok(inv[m].every(x=>x.evidence),`${m}: evidence ledgers`);ok(inv[m].every(x=>x.financeProductId),`${m}: finance mapping`);ok(inv[m].every(x=>x.insuranceProductId),`${m}: insurance mapping`);}
ok(providers.finance.length>=6,'finance provider catalogue');ok(providers.insurance.length>=6,'insurance provider catalogue');
near(transferDuty(1210000),0,'duty boundary 1');near(transferDuty(1663800),13614,'duty boundary 2');near(transferDuty(2329300),53544,'duty boundary 3');near(transferDuty(2994800),106784,'duty boundary 4');near(transferDuty(13310000),1241456,'duty boundary 5');near(transferDuty(14000000),1241456+690000*.13,'duty top bracket');
const vatEx=propertyVAT(1000000,{applicable:true,rate:15,priceIncludesVat:false});near(vatEx.amount,150000,'VAT excluded price');near(vatEx.grossConsideration,1150000,'VAT gross consideration');
const vatIn=propertyVAT(1150000,{applicable:true,rate:15,priceIncludesVat:true});near(vatIn.amount,150000,'VAT included price');near(vatIn.grossConsideration,1150000,'VAT included gross');near(propertyVAT(1000000,{applicable:false}).amount,0,'non VAT property');
const f0=financeQuote({price:100000,deposit:10000,rate:0,term:10,balloonPct:0,monthlyFee:0,initiationFee:0});near(f0.monthlyPayment,9000,'zero-rate payment');near(f0.totalPaid,100000,'zero-rate total');
const fb=financeQuote({price:100000,deposit:0,rate:12,term:12,balloonPct:20,monthlyFee:0,initiationFee:0});near(fb.balloon,20000,'balloon amount');const r=.12/12;near(fb.basePayment*(1-Math.pow(1+r,-12))/r+fb.balloon/Math.pow(1+r,12),100000,'balloon PV equation');ok(fb.financeCharges>0,'positive-rate finance charges');
for(const m of ['automotive','property','jewellery']){for(const raw of inv[m]){const a={...raw,assetType:m};const out=calcAssetOutcome(a,{finance:true,insurance:true,horizon:60,km:1500,fuelPrice:26.92,rate:10.5,term:72,deposit:0,balloonPct:10,monthlyFee:69,initiationFee:1200,exitScenario:'future'});ok(Number.isFinite(out.outcome),`${m} ${raw.id}: finite outcome`);ok(out.status==='CALCULATED',`${m} ${raw.id}: calculated`);ok(out.financeQuote.balloon>=0,`${m} ${raw.id}: finance balloon valid`);}}
const base={...inv.automotive[0],assetType:'automotive'};const noFin=calcAssetOutcome(base,{finance:false,insurance:false,horizon:60,km:1500,fuelPrice:26.92});const fin=calcAssetOutcome(base,{finance:true,insurance:false,horizon:60,km:1500,fuelPrice:26.92,rate:10.5,term:72,monthlyFee:69,initiationFee:1200});const insured=calcAssetOutcome(base,{finance:true,insurance:true,horizon:60,km:1500,fuelPrice:26.92,rate:10.5,term:72,monthlyFee:69,initiationFee:1200});ok(fin.financeCharges>0,'finance changes charges');ok(insured.insurance>0,'insurance adds cost');ok(insured.outcome<fin.outcome,'insurance reduces outcome');ok(noFin.financeCharges===0,'finance off removes charges');
const prop={...inv.property.find(x=>x.vatApplicable===false),assetType:'property'};const po=calcAssetOutcome(prop,{finance:false,insurance:false,horizon:60});near(po.detail.transferDuty,transferDuty(prop.price),'property duty feeds outcome');ok(po.detail.rentalIncome>0,'property rental income');
const vatProp={...inv.property.find(x=>x.vatApplicable===true),assetType:'property'};const vo=calcAssetOutcome(vatProp,{finance:false,insurance:false,horizon:60});near(vo.detail.transferDuty,0,'VAT property has zero transfer duty');ok(vo.detail.vatAmount>0,'VAT property includes VAT acquisition amount');ok(vo.financeBase>vo.purchasePrice,'VAT excluded property finance base is gross');
const jew={...inv.jewellery[0],assetType:'jewellery'};const jf=calcAssetOutcome(jew,{finance:false,insurance:false,horizon:60,exitScenario:'fairMarket'});const jt=calcAssetOutcome(jew,{finance:false,insurance:false,horizon:60,exitScenario:'trade'});const js=calcAssetOutcome(jew,{finance:false,insurance:false,horizon:60,exitScenario:'scrap'});near(jf.residual,jew.fairMarketValue,'jewellery fair market exit');near(jt.residual,jew.tradeValue,'jewellery trade exit');near(js.residual,jew.scrapValue,'jewellery scrap exit');ok(jt.outcome<jf.outcome,'trade outcome differs');ok(js.outcome<jt.outcome,'scrap outcome differs');
const iq=insuranceQuote(base,providers.insurance.find(x=>x.id==='INS-A'));ok(iq.premiumMonthly>0,'insurance quote premium');ok(iq.sumInsured===base.market,'automotive insurance basis');const qout=calcAssetOutcome(base,{finance:false,insurance:true,insuranceMonthly:iq.premiumMonthly,horizon:12,km:1500,fuelPrice:26.92});near(qout.insurance,iq.premiumMonthly*12,'selected insurance product feeds outcome');
const cmp=compareAssets([base,{...inv.automotive[1],assetType:'automotive'}],{finance:false,insurance:false,horizon:60});ok(cmp.length===2&&cmp.every(x=>x.outcome.status==='CALCULATED'),'comparison central engine');
for(const token of ['Automotive','Property','Fine Jewellery','Finance','Insurance','Evidence','ADVERTISEMENT','75 / 25','Affordability'])ok(html.includes(token),`HTML has ${token}`);for(const token of ['REAL-WORLD OUTCOME','Exit scenario'])ok(app.includes(token),`APP has ${token}`);
for(const token of ['calcAssetOutcome','compareAssets','financeQuote','insuranceQuote','propertyVAT','transferDuty','renderEvidence','renderSources','toggleCompare','switchMarket'])ok(app.includes(token),`app wires ${token}`);
console.log(`VECTORI 1.1 simulation suite: ${passed} assertions PASS`);
