import {money,pct,transferDuty,calcOutcome,evidenceFor} from './engine.js';
const state={market:'automotive',items:[],selected:null,compare:new Set(),finance:true,insurance:true,search:'',deposit:0,rate:10.5,term:72,balloon:0,horizon:60,km:1500};
let DATA=null;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function label(m){return m==='automotive'?'Automotive':m==='property'?'Property':'Fine Jewellery'}
function assetIcon(m){return m==='automotive'?'◈':m==='property'?'⌂':'◇'}
function render(){
 $('#marketName').textContent=label(state.market); $('#count').textContent=`${state.items.length} variants`; $('#search').value=state.search;
 $$('.market-tab').forEach(b=>b.classList.toggle('active',b.dataset.market===state.market));
 const q=state.search.toLowerCase(); const items=state.items.filter(x=>(x.name+x.dealer+(x.location||'')).toLowerCase().includes(q));
 $('#grid').innerHTML=items.map(card).join('');
 const dist={};items.forEach(x=>dist[x.dealer]=(dist[x.dealer]||0)+1); $('#dealerMix').innerHTML=Object.entries(dist).map(([d,c])=>`<span>${d} · ${c}</span>`).join('');
 $$('.compare-btn').forEach(b=>b.onclick=()=>{const id=b.dataset.id;if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size<3)state.compare.add(id);render();renderCompare();});
 $$('.intel-btn').forEach(b=>b.onclick=()=>select(b.dataset.id,true));
 $('#compareCount').textContent=state.compare.size;
}
function card(x){const gap=Math.round((x.market-x.price)/x.price*1000)/10;const sub=state.market==='property'?`${x.location} · ${x.type}`:state.market==='jewellery'?`${x.metal} · ${x.purity} · ${x.stoneCt}ct ${x.stone}`:`${x.year} · ${x.mileage.toLocaleString()} km · ${x.fuel}`;return `<article class="asset-card ${state.selected?.id===x.id?'selected':''}"><div class="asset-art"><span>${assetIcon(state.market)}</span><small>${x.id}</small></div><div class="asset-body"><div class="eyebrow">${x.dealer} · ${x.status.replaceAll('_',' ')}</div><h3>${x.name}</h3><p>${sub}</p><div class="price-row"><strong>${money(x.price)}</strong><span>Ref ${money(x.market)}</span></div><div class="tags"><span>${gap>=0?'+':''}${gap}% ref gap</span><span>${state.market==='property'?'Scenario':state.market==='jewellery'?'Valuation':'Market reference'}</span></div><div class="card-actions"><button class="ghost compare-btn" data-id="${x.id}">${state.compare.has(x.id)?'Remove compare':'Compare'}</button><button class="primary intel-btn" data-id="${x.id}">Intelligence</button></div></div></article>`}
function select(id,scroll=false){state.selected=state.items.find(x=>x.id===id); if(!state.selected)return; $('#calc').classList.add('open');fillCalc();renderDecision();if(scroll)$('#calc').scrollIntoView({behavior:'smooth',block:'start'});render();}
function fillCalc(){const x=state.selected;$('#calcAsset').textContent=x.name;$('#calcPrice').value=x.price;$('#deposit').value=state.deposit;$('#rate').value=state.rate;$('#term').value=state.term;$('#balloon').value=state.balloon;$('#horizon').value=state.horizon;$('#km').value=state.km;$('#finance').checked=state.finance;$('#insurance').checked=state.insurance;}
function renderDecision(){if(!state.selected)return;const x=state.selected;const out=calcOutcome({...x,assetType:state.market},{finance:state.finance,insurance:state.insurance,deposit:Number($('#deposit').value)||0,rate:Number($('#rate').value)||0,term:Number($('#term').value)||72,balloonPct:Number($('#balloon').value)||0,horizon:Number($('#horizon').value)||60,km:Number($('#km').value)||1500});state.last=out;$('#outcome').innerHTML=`<div class="outcome-main"><div><span class="eyebrow">REAL-WORLD OUTCOME · ${out.status}</span><h2>${money(out.economicPosition)}</h2><p>Modelled economic position after the selected horizon, using the current demo scenario inputs.</p></div><div class="outcome-grid"><div><span>Purchase</span><b>${money(out.purchasePrice)}</b></div><div><span>Acquisition</span><b>${money(out.acquisitionCosts)}</b></div><div><span>Ownership</span><b>${money(out.ownershipCosts)}</b></div><div><span>Finance</span><b>${money(out.financeCost)}</b></div><div><span>Insurance</span><b>${money(out.insuranceCost)}</b></div><div><span>Exit costs</span><b>${money(out.exitCosts)}</b></div></div></div><div class="evidence"><div class="section-head"><h3>Evidence ledger</h3><span>Demo status is explicit</span></div>${evidenceFor(x).map(e=>`<div class="e-row"><span>${e.field}</span><b>${e.status}</b><small>${e.source}</small></div>`).join('')}</div>`;$('#transferDuty').textContent=state.market==='property'?money(transferDuty(x.price)):'—';}
function renderCompare(){const arr=state.items.filter(x=>state.compare.has(x.id));let html='';if(arr.length){html='<div class=\"compare-head\"><span>Comparison set</span><b>'+arr.length+'/3</b></div>'+arr.map(x=>'<div class=\"compare-row\"><b>'+x.name+'</b><span>'+money(x.price)+'</span><span>'+money(x.market)+'</span><button data-id=\"'+x.id+'\" class=\"remove-compare\">×</button></div>').join('')}else{html='<div class=\"empty\">Select up to three assets to compare.</div>'}$('#compare').innerHTML=html;$$('.remove-compare').forEach(b=>b.onclick=()=>{state.compare.delete(b.dataset.id);render();renderCompare()})}

function bind(){
 $$('.market-tab').forEach(b=>b.onclick=()=>{state.market=b.dataset.market;state.items=DATA[state.market].map(x=>({...x,assetType:state.market}));state.selected=null;state.compare.clear();$('#calc').classList.remove('open');render();renderCompare();});
 $('#search').oninput=e=>{state.search=e.target.value;render()};
 $('#run').onclick=()=>{state.finance=$('#finance').checked;state.insurance=$('#insurance').checked;state.deposit=Number($('#deposit').value)||0;state.rate=Number($('#rate').value)||0;state.term=Number($('#term').value)||72;state.balloon=Number($('#balloon').value)||0;state.horizon=Number($('#horizon').value)||60;state.km=Number($('#km').value)||1500;renderDecision()};
 $('#closeCalc').onclick=()=>$('#calc').classList.remove('open');
 $('#reset').onclick=()=>{state.search='';state.deposit=0;state.rate=10.5;state.term=72;state.balloon=0;state.horizon=60;state.km=1500;render();};
}
fetch('data/inventory.json').then(r=>r.json()).then(d=>{DATA=d;state.items=d.automotive.map(x=>({...x,assetType:'automotive'}));bind();render();renderCompare();});
