export const DATA_STATUS={OBSERVED:'OBSERVED',VERIFIED:'VERIFIED',PROVIDER_SUPPLIED:'PROVIDER_SUPPLIED',USER_PROVIDED:'USER_PROVIDED',CALCULATED:'CALCULATED',ASSUMED:'ASSUMED',ESTIMATED:'ESTIMATED',MISSING:'MISSING'};
export function money(n){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n)||0)}
export function pct(n){return `${(Number(n)||0).toFixed(1)}%`}
export function transferDuty(v){v=Number(v)||0;if(v<=1210000)return 0;if(v<=1663800)return (v-1210000)*.03;if(v<=2329300)return 13614+(v-1663800)*.06;if(v<=2994800)return 53544+(v-2329300)*.08;if(v<=13310000)return 106784+(v-2994800)*.11;return 1241456+(v-13310000)*.13}
export function financePayment({price,deposit=0,rate=10.5,term=72,balloonPct=0,monthlyFee=0,initiationFee=0}){const principal=Math.max(0,price-deposit);const balloon=principal*(balloonPct/100);const r=rate/100/12;let payment;if(r===0)payment=(principal-balloon)/term;else payment=(principal-(balloon/(1+r)**term))*r/(1-(1+r)**(-term));return {principal,balloon,instalment:payment+monthlyFee,totalScheduled:(payment+monthlyFee)*term+balloon+initiationFee,initiationFee,monthlyFee}}
export function calcOutcome(asset,{finance=true,insurance=true,deposit=0,rate=10.5,term=72,balloonPct=0,monthlyFee=69,initiationFee=1200,horizon=60,fuelPrice=26.92,km=1500}){
 const p=asset.price;let ownership=0,acq=0,exit=0,insuranceCost=0,financeCost=0, details={};
 if(asset.assetType==='property'){acq=transferDuty(p);ownership=(asset.ratesMonthly+asset.leviesMonthly+asset.maintenanceMonthly)*horizon;insuranceCost=asset.insuranceMonthly*horizon;exit=asset.futureValue*(asset.saleCostPct/100);details={transferDuty:acq,municipalAndMaintenance:ownership,insurance:insuranceCost,saleCosts:exit,rentalIncome:asset.rentalMonthly*horizon};}
 else if(asset.assetType==='jewellery'){acq=0;ownership=(asset.storageMonthly)*horizon;insuranceCost=insurance?asset.insuranceMonthly*horizon:0;exit=asset.futureValue*(asset.resaleCostPct/100);details={valuation:asset.valuation,storage:ownership,insurance:insuranceCost,resaleCosts:exit};}
 else {const fuel=(asset.consumption/100)*km*fuelPrice*horizon;ownership=asset.ownershipMonthly*horizon+fuel;insuranceCost=insurance?asset.insuranceMonthly*horizon:0;exit=asset.futureValue;details={fuel,fuelPrice,ownershipBase:asset.ownershipMonthly*horizon};}
 if(finance){const f=financePayment({price:p,deposit,rate,term,balloonPct,monthlyFee,initiationFee});financeCost=f.totalScheduled-(p-deposit);details.finance=f;}
 const totalCash=deposit+acq+ownership+insuranceCost+financeCost+Math.max(0,exit); const economicPosition=asset.assetType==='property'?(asset.futureValue+details.rentalIncome-totalCash):(asset.futureValue-totalCash);
 return {assetId:asset.id,purchasePrice:p,acquisitionCosts:acq,ownershipCosts:ownership,insuranceCost,financeCost,exitCosts:exit,totalCashOut:totalCash,economicPosition,details,status:'CALCULATED'};
}
export function evidenceFor(asset){return [{field:'identity',status:'DEMO',source:asset.source},{field:'price',status:'DEMO',source:'Demo catalogue'},{field:'marketReference',status:'DEMO',source:'Demo catalogue'},{field:'futureValue',status:'ESTIMATED',source:'Scenario input'},{field:'regulatoryChecks',status:'MISSING_IN_DEMO',source:'Production verification required'}]}
