let vehicles=[]; let financeData=null; let insuranceData=null; let compare=[]; let lastFinance=null; let lastInsurance=null;
const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(v)):'Insufficient data';
const numFmt=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-ZA').format(Number(v)):'—';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function load(){
  const [v,f,i]=await Promise.all([fetch('./data/inventory.json'),fetch('./finance-data.json'),fetch('./insurance-data.json')]);
  vehicles=await v.json(); financeData=await f.json(); insuranceData=await i.json();
  document.getElementById('inventoryStatus').textContent=`${vehicles.length} demo records • source-derived • not live stock`;
  populateVehicleSelectors(); renderVehicles();
}
function populateVehicleSelectors(){
  const opts='<option value="">Select vehicle</option>'+vehicles.map(v=>`<option value="${esc(v.listing_id||v.id)}">${esc(v.year||'')} ${esc(v.make||'')} ${esc(v.model||'')} ${esc(v.variant||'')}</option>`).join('');
  document.getElementById('finVehicle').innerHTML=opts;
  document.getElementById('finVehicle').addEventListener('change',()=>{const v=findVehicle(document.getElementById('finVehicle').value);if(v){document.getElementById('finPrice').value=v.price||'';document.getElementById('tcPrice').value=v.price||'';document.getElementById('tcConsumption').value=v.consumption||'';document.getElementById('insVehicleValue').value=v.price||'';}});
}
function findVehicle(id){return vehicles.find(v=>String(v.listing_id||v.id)===String(id));}
function vehicleName(v){return [v.year,v.make,v.model,v.variant].filter(Boolean).join(' ')||'Vehicle';}
function renderVehicles(){
  const q=(document.getElementById('search').value||'').toLowerCase(), prov=document.getElementById('province').value;
  const maxP=Number(document.getElementById('maxPrice').value)||Infinity,maxM=Number(document.getElementById('maxMileage').value)||Infinity;
  let list=vehicles.filter(v=>{const text=vehicleName(v).toLowerCase();return(!q||text.includes(q))&&(!prov||String(v.location||'').toLowerCase().includes(prov.toLowerCase()))&&Number(v.price)<=maxP&&Number(v.mileage||0)<=maxM;});
  const sort=document.getElementById('sort').value;if(sort==='mileage')list.sort((a,b)=>(a.mileage||Infinity)-(b.mileage||Infinity));else if(sort==='year')list.sort((a,b)=>(b.year||0)-(a.year||0));else list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));
  document.getElementById('vehicleGrid').innerHTML=list.slice(0,60).map(v=>`<article class="vehicle-card"><div class="meta">${esc(v.location||'Location not supplied')} • ${esc(v.transmission||'Transmission not supplied')}</div><h3>${esc(vehicleName(v))}</h3><div class="price">${money(v.price)}</div><div class="meta">${numFmt(v.mileage||0)} km • ${esc(v.fuel||'Fuel not supplied')} ${v.consumption?`• ${esc(v.consumption)} L/100km`:''}</div><div class="badges"><span class="badge">${esc(v.dealer_or_private||'Source type unknown')}</span><span class="badge">Evidence: source-derived</span></div><div class="actions"><button class="btn primary" onclick="selectVehicle('${esc(v.listing_id||v.id)}')">Use this vehicle</button><button class="btn secondary" onclick="toggleCompare('${esc(v.listing_id||v.id)}')">${compare.some(x=>String(x.listing_id||x.id)===String(v.listing_id||v.id))?'Remove':'Compare'}</button></div></article>`).join('')||'<div class="empty">No vehicles match these filters.</div>';
}
function selectVehicle(id){const v=findVehicle(id);if(!v)return;document.getElementById('finVehicle').value=id;document.getElementById('finPrice').value=v.price||'';document.getElementById('tcPrice').value=v.price||'';document.getElementById('tcConsumption').value=v.consumption||'';document.getElementById('insVehicleValue').value=v.price||'';document.getElementById('finance').scrollIntoView({behavior:'smooth'});}
function toggleCompare(id){const idx=compare.findIndex(v=>String(v.listing_id||v.id)===String(id));if(idx>=0)compare.splice(idx,1);else if(compare.length<6){const v=findVehicle(id);if(v)compare.push(v);}renderVehicles();renderCompare();}
function clearCompare(){compare=[];renderCompare();renderVehicles();}
function renderCompare(){if(!compare.length){document.getElementById('compareArea').innerHTML='<div class="empty">Select vehicles above to build a comparison.</div>';return;}const rows=[['Price','price',money],['Mileage','mileage',numFmt],['Year','year',numFmt],['Fuel','fuel',x=>x||'Insufficient data'],['Consumption','consumption',x=>x?`${x} L/100km`:'Insufficient data'],['Transmission','transmission',x=>x||'Insufficient data'],['Dealer/source','dealer_or_private',x=>x||'Insufficient data'],['Location','location',x=>x||'Insufficient data']];document.getElementById('compareArea').innerHTML=`<table class="compare-table"><thead><tr><th>Evidence</th>${compare.map(v=>`<th>${esc(vehicleName(v))}<br><button class="btn secondary" style="margin-top:6px" onclick="toggleCompare('${esc(v.listing_id||v.id)}')">Remove</button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td>${compare.map(v=>`<td>${esc(r[2](v[r[1]]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function startBudget(){document.getElementById('budgetMonthly').focus();document.getElementById('find').scrollIntoView({behavior:'smooth'});}
function budgetSearch(){const budget=Number(document.getElementById('budgetMonthly').value)||0;document.getElementById('maxPrice').value=Math.max(0,Math.round(budget*45));document.getElementById('sort').value='price';renderVehicles();document.getElementById('find').scrollIntoView({behavior:'smooth'});}
function runFinance(){const input={price:Number(document.getElementById('finPrice').value),deposit:Number(document.getElementById('finDeposit').value),tradeIn:Number(document.getElementById('finTrade').value),rate:Number(document.getElementById('finRate').value),term:Number(document.getElementById('finTerm').value),balloonPct:Number(document.getElementById('finBalloon').value),adminFee:Number(document.getElementById('finAdmin').value),initiationFee:Number(document.getElementById('finInit').value),creditLifePerR1000:Number(document.getElementById('finCreditLife').value)};const products=selectFinanceProducts(financeData,input);if(!products.length){document.getElementById('financeResults').innerHTML='<div class="empty">No verified product structure in the research dataset matches those term/balloon inputs.</div>';return;}const product=products[0];lastFinance=financeScenario(input,product);document.getElementById('financeResults').innerHTML=`<div class="metric-grid"><div class="metric"><small>Principal</small><strong>${money(lastFinance.principal)}</strong></div><div class="metric"><small>Monthly instalment</small><strong>${money(lastFinance.payment)}</strong></div><div class="metric"><small>Balloon</small><strong>${money(lastFinance.balloon)}</strong></div><div class="metric"><small>Total interest</small><strong>${money(lastFinance.totalInterest)}</strong></div><div class="metric"><small>Admin fees</small><strong>${money(lastFinance.totalAdmin)}</strong></div><div class="metric"><small>Total finance cash outlay*</small><strong>${money(lastFinance.totalCost)}</strong></div></div><p class="meta">*Includes deposit/trade-in treatment, instalments, balloon, admin and credit-life input. It is an estimate, not a provider quote.</p><div class="status">Using ${esc(lastFinance.provider)} • ${esc(lastFinance.product)} • evidence ${esc(lastFinance.evidence)}</div>`;showFinanceProviders();}
function showFinanceProviders(){const input={term:Number(document.getElementById('finTerm').value),balloonPct:Number(document.getElementById('finBalloon').value)};const products=selectFinanceProducts(financeData,input);document.getElementById('financeProviders').innerHTML=products.map(p=>`<div class="provider-card"><h4>${esc(p.provider)} — ${esc(p.name)}</h4><p>Structure: ${esc(p.structures.join(', '))}</p><p>Term: ${p.termMin||'provider'}–${p.termMax||'specific'} months • Balloon: ${p.balloonSupported?(p.balloonMaxPct?`up to ${p.balloonMaxPct}% published`: 'supported; limit quote-dependent'):'not modelled'}</p><p>Rate type: ${esc(p.rateTypes.join(', '))}</p><p>${esc(p.notes)}</p><div class="source">Evidence: ${esc(p.evidence)} • source IDs: ${esc(p.sourceIds.join(', '))}</div></div>`).join('')||'<div class="empty">No matching verified structures.</div>';}
function runInsurance(){const input={premium:Number(document.getElementById('insPremium').value),excess:Number(document.getElementById('insExcess').value),voluntaryExcess:Number(document.getElementById('insVoluntary').value),additionalExcess:Number(document.getElementById('insAdditional').value),vehicleValue:Number(document.getElementById('insVehicleValue').value),financeSettlement:Number(document.getElementById('insSettlement').value),insurerPayout:Number(document.getElementById('insPayout').value)};const p=selectInsuranceProducts(insuranceData)[0];lastInsurance=insuranceScenario(input,p);document.getElementById('insuranceResults').innerHTML=`<div class="metric-grid"><div class="metric"><small>Monthly premium</small><strong>${money(lastInsurance.premium)}</strong></div><div class="metric"><small>Annual premium</small><strong>${money(lastInsurance.annual)}</strong></div><div class="metric"><small>Total applicable excess</small><strong>${money(lastInsurance.excess)}</strong></div><div class="metric"><small>Total-loss claim cash exposure</small><strong>${money(lastInsurance.claimOutOfPocket.totalLoss)}</strong></div><div class="metric"><small>Credit shortfall input</small><strong>${money(lastInsurance.creditShortfall)}</strong></div></div><p class="meta">The premium above is an entered quote/demo assumption. VECTORI does not infer or invent an insurer price.</p>`;showInsuranceProviders();}
function showInsuranceProviders(){const products=selectInsuranceProducts(insuranceData);document.getElementById('insuranceProviders').innerHTML=products.map(p=>`<div class="provider-card"><h4>${esc(p.provider)} — ${esc(p.name)}</h4><p>Cover: ${esc(p.cover)} • Insured value: ${esc(p.insuredValue)}</p><p>Excess: ${esc(p.excess)}</p><p>Liability: ${esc(p.liability||'policy dependent')} • Roadside: ${p.roadside===true?'published':p.roadside===false?'not published':'not established in dataset'}</p><p>Credit shortfall: ${p.creditShortfall===true?'published add-on':p.creditShortfall===false?'not published':'not established in dataset'}</p><div class="source">Evidence: ${esc(p.evidence)} • source IDs: ${esc(p.sourceIds.join(', '))}</div></div>`).join('');}
function runTotalCost(){if(!lastFinance)runFinance();if(!lastInsurance)runInsurance();const input={price:Number(document.getElementById('tcPrice').value),consumption:Number(document.getElementById('tcConsumption').value),monthlyKm:Number(document.getElementById('tcKm').value),fuelPrice:Number(document.getElementById('tcFuel').value),maintenancePerKm:Number(document.getElementById('tcMaintenance').value),tyreSetCost:Number(document.getElementById('tcTyreCost').value),tyreLife:Number(document.getElementById('tcTyreLife').value),licenceAnnual:Number(document.getElementById('tcLicence').value),futureValue:Number(document.getElementById('tcFuture').value),horizon:Number(document.getElementById('tcHorizon').value),grossIncome:Number(document.getElementById('tcIncome').value),otherDebt:Number(document.getElementById('tcDebt').value),livingCosts:Number(document.getElementById('tcLiving').value),otherVehicleCosts:Number(document.getElementById('tcOther').value),insurance:lastInsurance?.premium||0};const t=totalOwnership(input,lastFinance,lastInsurance||{premium:0});const s=stressTest({...input,rate:lastFinance.rate,balloonPct:lastFinance.balloonPct,adminFee:lastFinance.admin,initiationFee:lastFinance.initiation,creditLifePerR1000:0},lastFinance,lastInsurance||{premium:0});document.getElementById('totalResults').innerHTML=`<div class="metric-grid"><div class="metric"><small>Finance instalment</small><strong>${money(lastFinance.payment)}</strong></div><div class="metric"><small>Insurance</small><strong>${money(lastInsurance?.premium||0)}</strong></div><div class="metric"><small>Fuel</small><strong>${money(t.fuel)}</strong></div><div class="metric"><small>Maintenance</small><strong>${money(t.maintenance)}</strong></div><div class="metric"><small>Tyres</small><strong>${money(t.tyres)}</strong></div><div class="metric"><small>Licence reserve</small><strong>${money(t.licence)}</strong></div><div class="metric"><small>Monthly cash burden</small><strong>${money(t.cash)}</strong></div><div class="metric"><small>Cash remaining</small><strong class="${t.cashRemaining<0?'danger':t.cashRemaining<5000?'warn':'good'}">${money(t.cashRemaining)}</strong></div><div class="metric"><small>Economic cost</small><strong>${t.economic===null?'Insufficient data':money(t.economic)}</strong></div><div class="metric"><small>Stress-test burden</small><strong class="warn">${money(s.total.cash)}</strong></div></div><p class="meta">Stress test: +1 percentage point finance rate, +20% fuel, +15% insurance and +20% maintenance. These are VECTORI stress assumptions, not lender/insurer forecasts.</p>`;}
function dealerRequest(){document.getElementById('dealerMsg').innerHTML='<div class="status" style="margin-top:15px">Demo onboarding request created locally. Production onboarding requires verified dealership authority and an integration contract.</div>';}
window.addEventListener('DOMContentLoaded',()=>load().catch(e=>{document.getElementById('inventoryStatus').textContent='Inventory unavailable — no data fabricated';console.error(e);}));
